[package]
name = "hdwallet"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base58 = "0.2.0"
ecdsa = "0.14.8"
hex = "0.4.3"
k256 = "0.11.6"
rand_core = "0.6.4"
ripemd = "0.1.2"
sha2 = "0.10.6"
